### PR TITLE
Added method to plot the mean arity of nodes.

### PR DESCRIPTION
**Pull request by savitakartik**
Changed 'zoom' to 'region' in parameter names for consistency. 
Closes issue #10

### CODE REVIEW

**Comment by savitakartik** [comment]
Would we want to look at mean node arity in specific genomic regions?
Do we need a `max_arity` parameter for the histogram?

**Comment by savitakartik** [comment]
> Can you paste in an example of what it looks like please?
> 
> How long does it take to compute the stat for the unified genealogy trees?

image

took 1m48s for the long arm of chr 2 (256_897 trees, 1475_035 nodes).

**Comment by jeromekelleher** [comment]
> took 1m48s for the long arm of chr 2 (256_897 trees, 1475_035 nodes).

That's too long I think, we need a quicker way to summarise

**Comment by jeromekelleher** [comment]
(I didn't get notified that this was marked as ready - I think you need to ping me explicitly for this stuff)

**Comment by savitakartik** [comment]
> (I didn't get notified that this was marked as ready - I think you need to ping me explicitly for this stuff)

Oh, I see. I assumed you would be notified. Thanks for letting me know.

**Comment by jeromekelleher** [comment]
Looks good - you probably want to add plot_mean_arity to the markdown now?

**Comment by jeromekelleher** [comment]
(Easiest way now is to make the change, then do ``git commit -a --amend``, and the change will then be added to this commit. You can then force-push)

**Pull request merged**
