### PR TITLE
Add loading indicator and error handling to pages

### PR DESCRIPTION
**Pull request by benjeffery**
Adds a spinner to indicate that the page is being prepared, and display an error with stacktrace if the page code errors.
Screenshot from 2023-08-29 23-17-16

### CODE REVIEW

**Comment by jeromekelleher** [comment]
What do you think @savitakartik ?

**Comment by savitakartik** [comment]
Looks good to me.

I love both features. A really minor thing I find with the loading indicator is that it doesn't show up for the very first page you click on.  Works fine every other time. The error display is also really nice, makes it really easy to debug.

Thanks so much, @benjeffery !

**Comment by savitakartik** [comment]
I'm not sure I understand why the linting check failed though. Seems like formatting changes, so not sure why they didn't get automatically fixed?

**Comment by benjeffery** [comment]
> I'm not sure I understand why the linting check failed though. Seems like formatting changes, so not sure why they didn't get automatically fixed?

My bad, didn't install pre-commit locally!

**Review by savitakartik — APPROVED** [review]

**Pull request merged**
