### PR TITLE
changes to mutation panel

### PR DESCRIPTION
**Pull request by savitakartik**
partial fix for issue #66
fixes issue #65

- added an index column to mutations df so we can display mutation ID on hover (not sure if this is the right way to do this)
- added test case for above
- coloured mutations by number of inheritors
- changed tooltip information on hover to display mutation ID, number of parents, inheritors and descendants.

### CODE REVIEW

**Comment by savitakartik** [comment]
https://github.com/tskit-dev/tsinfer-qc/assets/25925005/f72fa2e3-10ee-429b-9c54-444a6f1b48c0

**Review by jeromekelleher — COMMENTED** [review]
LGTM - but ``id`` would be more consistent?

**Comment by jeromekelleher** [comment]
Needs a rebase @savitakartik

**Comment by savitakartik** [comment]
> Needs a rebase @savitakartik

Done (I think!)

**Comment by jeromekelleher** [comment]
@mergifyio rebase

**Review by jeromekelleher — APPROVED** [review]

**Pull request merged**
